### ISSUE TITLE
Add Some Features

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [mikethedj4/Polyrise#1]
Example:

- First Make A Page to Choose Template then Open Editor
- Add Option to Create Add Multiple Page Template (like Mobirise)

Now tell me what you are thinking

**Comment by michaelsboost** [comment]
Polyrise was discontinued for quite sometime as I pursued other ventures. For the past several months I been working hard on rebuilding it. It's completely re-engineered from top to bottom so now you have complete creative freedom for website design on a phone.
